# Parameters:
#   modules: <modules artifact name>

jobs:
  - template: ./conda-win.yml
    parameters:
      vmImage: windows-2019
      vs: 2019
      modules: modules
  - template: ./conda-linux.yml
    parameters:
      distribution: rockylinux
      version: [8]
      modules: ${{ parameters.modules }}
      template: ./unix-conda-build.yml
  - template: ./conda-osx.yml
    parameters:
      vmImage: [12]
      xcode_version: [13, 4, 1]
      modules: modules
      template: ./unix-conda-build.yml
