# Parameters:
#   modules: <modules artifact name>

jobs:
  - template: ./conda-win.yml
    parameters:
      vmImage: windows-2019
      vs: 2019
      modules: modules
  - template: ./conda-linux.yml
    parameters:
      distribution: centos
      version: [6]
      modules: modules
      template: ./unix-conda-build.yml
  - template: ./conda-osx.yml
    parameters:
      vmImage: [11]
      xcode_version: [12, 5, 1]
      modules: modules
      template: ./unix-conda-build.yml
